theme: jekyll-theme-minimal
avatar: https://user-images.githubusercontent.com/55975428/100692409-5dc59f00-33bd-11eb-80f0-7db7707c1948.PNG
description: Quoc Thinh Luu's resume
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
